# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/orland/flight_control_simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/orland/flight_control_simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orland/flight_control_simulation/CMakeFiles /home/orland/flight_control_simulation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orland/flight_control_simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flight_control_simulation

# Build rule for target.
flight_control_simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flight_control_simulation
.PHONY : flight_control_simulation

# fast build rule for target.
flight_control_simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/build
.PHONY : flight_control_simulation/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/main.cpp.s
.PHONY : main.cpp.s

src/control_system.o: src/control_system.cpp.o
.PHONY : src/control_system.o

# target to build an object file
src/control_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/control_system.cpp.o
.PHONY : src/control_system.cpp.o

src/control_system.i: src/control_system.cpp.i
.PHONY : src/control_system.i

# target to preprocess a source file
src/control_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/control_system.cpp.i
.PHONY : src/control_system.cpp.i

src/control_system.s: src/control_system.cpp.s
.PHONY : src/control_system.s

# target to generate assembly for a file
src/control_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/control_system.cpp.s
.PHONY : src/control_system.cpp.s

src/flight_dynamics.o: src/flight_dynamics.cpp.o
.PHONY : src/flight_dynamics.o

# target to build an object file
src/flight_dynamics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/flight_dynamics.cpp.o
.PHONY : src/flight_dynamics.cpp.o

src/flight_dynamics.i: src/flight_dynamics.cpp.i
.PHONY : src/flight_dynamics.i

# target to preprocess a source file
src/flight_dynamics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/flight_dynamics.cpp.i
.PHONY : src/flight_dynamics.cpp.i

src/flight_dynamics.s: src/flight_dynamics.cpp.s
.PHONY : src/flight_dynamics.s

# target to generate assembly for a file
src/flight_dynamics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/flight_dynamics.cpp.s
.PHONY : src/flight_dynamics.cpp.s

src/gps_sensor.o: src/gps_sensor.cpp.o
.PHONY : src/gps_sensor.o

# target to build an object file
src/gps_sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/gps_sensor.cpp.o
.PHONY : src/gps_sensor.cpp.o

src/gps_sensor.i: src/gps_sensor.cpp.i
.PHONY : src/gps_sensor.i

# target to preprocess a source file
src/gps_sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/gps_sensor.cpp.i
.PHONY : src/gps_sensor.cpp.i

src/gps_sensor.s: src/gps_sensor.cpp.s
.PHONY : src/gps_sensor.s

# target to generate assembly for a file
src/gps_sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/gps_sensor.cpp.s
.PHONY : src/gps_sensor.cpp.s

src/imu_sensor.o: src/imu_sensor.cpp.o
.PHONY : src/imu_sensor.o

# target to build an object file
src/imu_sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/imu_sensor.cpp.o
.PHONY : src/imu_sensor.cpp.o

src/imu_sensor.i: src/imu_sensor.cpp.i
.PHONY : src/imu_sensor.i

# target to preprocess a source file
src/imu_sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/imu_sensor.cpp.i
.PHONY : src/imu_sensor.cpp.i

src/imu_sensor.s: src/imu_sensor.cpp.s
.PHONY : src/imu_sensor.s

# target to generate assembly for a file
src/imu_sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/imu_sensor.cpp.s
.PHONY : src/imu_sensor.cpp.s

src/sensor_model.o: src/sensor_model.cpp.o
.PHONY : src/sensor_model.o

# target to build an object file
src/sensor_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/sensor_model.cpp.o
.PHONY : src/sensor_model.cpp.o

src/sensor_model.i: src/sensor_model.cpp.i
.PHONY : src/sensor_model.i

# target to preprocess a source file
src/sensor_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/sensor_model.cpp.i
.PHONY : src/sensor_model.cpp.i

src/sensor_model.s: src/sensor_model.cpp.s
.PHONY : src/sensor_model.s

# target to generate assembly for a file
src/sensor_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight_control_simulation.dir/build.make CMakeFiles/flight_control_simulation.dir/src/sensor_model.cpp.s
.PHONY : src/sensor_model.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flight_control_simulation"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/control_system.o"
	@echo "... src/control_system.i"
	@echo "... src/control_system.s"
	@echo "... src/flight_dynamics.o"
	@echo "... src/flight_dynamics.i"
	@echo "... src/flight_dynamics.s"
	@echo "... src/gps_sensor.o"
	@echo "... src/gps_sensor.i"
	@echo "... src/gps_sensor.s"
	@echo "... src/imu_sensor.o"
	@echo "... src/imu_sensor.i"
	@echo "... src/imu_sensor.s"
	@echo "... src/sensor_model.o"
	@echo "... src/sensor_model.i"
	@echo "... src/sensor_model.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

